FROM python:3.10-slim

RUN apt update -y && apt install -y build-essential cmake git wget && mkdir /flask-test

WORKDIR /flask-test

RUN git clone https://github.com/ggerganov/llama.cpp.git && mkdir /flask-test/build && cd /flask-test/build && cmake .. && make && make install

RUN git clone https://github.com/meta-llama/llama3.git && bash llama3/download.sh 

ADD requirements.txt /flask-test/

RUN pip install --upgrade pip && pip install -r requirements.txt
